empl:
  uploadPath: D:/zhongwang/ems
  username: admin
  password: 123456
logging:
  level:
    root: info
    com.zhongwang: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.12.67:3306/em?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: admin
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 记录慢SQL
    logSlowSql: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
    database: 0
    host: 192.168.12.67
    password: em1921681267Zw!!@
    port: 6379
    timeout: 10000       # 连接超时时间 单位 ms（毫秒）
    #    cluster:
    #      nodes: 10.3.1.4:7000,10.3.1.4:7001,...,10.3.1.4:7008
    lettuce:
      pool:
        # 连接池中的最大空闲连接，默认值也是8
        max-idle: 100
        min-idle: 10       # 连接池中的最小空闲连接，默认值也是0
        max-active: 100     # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
        max-wait: 30      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出